CREATE TABLE  `sfm_dev`.`t_accesses` (
`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`CREATION_DATE` DATETIME NULL DEFAULT NULL ,
`MODIFICATION_DATE` DATETIME NULL DEFAULT NULL ,
`USER_ID` INT NOT NULL ,
`RESOURCE_ID` INT NOT NULL ,
`DURATION_TYPE` VARCHAR( 10 ) NOT NULL DEFAULT  'PERMANENT' ,
`START_DATE` DATETIME NULL DEFAULT NULL ,
`END_DATE` DATETIME NULL DEFAULT NULL
) ENGINE = INNODB;
