CREATE TABLE `sfm_dev`.`T_USERS` (
`ID` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`CREATION_DATE` DATETIME NULL DEFAULT NULL ,
`MODIFICATION_DATE` DATETIME NULL DEFAULT NULL ,
`USERNAME` VARCHAR( 30 ) NOT NULL ,
`PASSWORD` VARCHAR( 30 ) NOT NULL ,
`ACTIVATED` BOOLEAN NOT NULL ,
`LAST_CONNECTION_DATE` DATETIME NULL DEFAULT NULL
) ENGINE = INNODB;